# NumPy

## Overview

[NumPy](https://numpy.org/) is a library for Python, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. **NumPy is the fundamental package for scientific computing with Python**.

NumPy contains, among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

The most up-to-date **NumPy documentation** can be found at [Overview — NumPy v1.19.dev0 Manual](https://numpy.org/devdocs/). It includes a user guide, full reference documentation, and more.

To use NumPy and create plots, we need the following import statements:

In [1]:
import numpy as np
import matplotlib.pyplot as pp

## NumPy Arrays

NumPy provides an **N-dimensional array type**, the `ndarray`, which describes a *collection of "items" of the same type*. The items can be indexed using zero-based indexing.

All ndarrays are homogenous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way.

### Construction

The simplest way to **create a NumPy array is by converting a Python list**.

Let us create a 1D array.

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

The **array type** was inferred by NumPy based on the contents of the list. However, we can also specify the type.

In [3]:
a.dtype

dtype('int64')

In [7]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

The **number of dimensions (*1D, 2D, etc.*), shape (*nrows, ncols*), and size (*num elements*) of an array** is given by:

In [8]:
a.ndim, a.shape, a.size

(1, (5,), 5)

For a 2D array, we have:

In [10]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
b.ndim, b.shape, b.size

(2, (2, 4), 8)

There are **other ways to create arrays**.

We can **create an empty array**:

In [20]:
np.empty((3,3), 'd')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

We can **create an array of zeros**:

In [21]:
np.zeros((3,3), 'd')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

We can **create regularly-spaced arrays of numbers**:

- We can use `linspace()` to choose the number of elements between two extrema (e.g., 5 elements between 0 and 10).
- We can use `arange()` to choose a *step* to go between the two given elements.

In [26]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

We can create **arrays of random numbers**:

In [29]:
np.random.standard_normal((2,3))

array([[ 0.3413167 ,  1.07132952, -0.1922738 ],
       [ 1.26116876,  0.90395212, -1.548497  ]])

We can also create new arrays by composing existing ones if they have compatible shapes.

In [46]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], 'i')
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [47]:
b = np.zeros((2,4), 'i')
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [48]:
np.vstack([a,b])  # stack them vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [49]:
np.hstack([a,b])  # stack them horizontally

array([[1, 2, 3, 4, 0, 0, 0, 0],
       [5, 6, 7, 8, 0, 0, 0, 0]], dtype=int32)

We can **save and load NumPy arrays to and from disk** very simply. 

In [53]:
np.save('file_io/saved_array.npy', a)  # saving array 'a'

In [54]:
c = np.load('file_io/saved_array.npy')

In [55]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

### Conversion

We can **take the transpose of an array**:

In [50]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [52]:
a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int32)

### Operations